### PR TITLE
feat(TDI-46935): jdbc port as String

### PR DESCRIPTION
**Pull request by ypiel-talend**
https://jira.talendforge.org/browse/TDI-46935

### CODE REVIEW

**Review by Tanya5091 — APPROVED** [review]
LGTM

**Comment by olhava** [comment]
Please check if migration task is necessary

**Review by olhava — CHANGES_REQUESTED** [review]
Please check if migration task is necessary

**Review by olhava — APPROVED** [review]

**Review by Tanya5091 — APPROVED** [review]
LGTM

**Pull request closed without merging**
