### PR TITLE
fix(TDI-47954): Update netty dependency

### PR DESCRIPTION
**Pull request by dmytro-sylaiev**

### CODE REVIEW

**Review by clesaec — DISMISSED** [review]
:+1:

**Comment by ozhelezniak-talend** [comment]
Can we manage it with dependencyManager and globally?

**Review by clesaec — APPROVED** [review]
:+1:

**Comment by ozhelezniak-talend** [comment]
-ee and cloud-components too, please

**Review by dmytrogrygorenko — APPROVED** [review]

**Pull request merged**
