### PR TITLE
fix(TDI-45319): Add maven-shade-plugin

### PR DESCRIPTION
**Pull request by dmytro-sylaiev**

### CODE REVIEW

**Review by ovladyka — DISMISSED** [review]

**Comment by dmytro-sylaiev** [comment]
@undx please configure your IDEA for 4 spaces in tabs for xml files :)

**Review by undx — APPROVED** [review]
LGTM

**Review by undx — APPROVED** [review]
LGTM

**Review by undx — APPROVED** [review]
LGTM

**Pull request merged**
