### PR TITLE
TDI-45546 - Marketo unit test

### PR DESCRIPTION
**Pull request by clesaec**
https://jira.talendforge.org/browse/TDI-45546

Add unit test on marketo

### CODE REVIEW

**Review by undx — APPROVED** [review]
LGTM
Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

**Review by undx — APPROVED** [review]
LGTM
Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

**Review by undx — APPROVED** [review]
LGTM
Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

**Review by undx — APPROVED** [review]
LGTM
Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

**Review by undx — APPROVED** [review]
LGTM
Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

**Comment by clesaec** [comment]
> LGTM
> Just a question, for captures, I see the access token in payloads. This token is well time dependent and cannot be resused? (Otherwise, invalidate credentials)

Yes, it can't be reused.

**Pull request merged**
